apiVersion: v1
kind: ConfigMap
metadata:
  name: fission-function-global-configmap
  namespace: fission-secret-configmap
data:
  kafka-broker-list: "http://127.0.0.1:9092"  # kafka默认连接地址
  pushgateway-url: "http://127.0.0.1:9091"    # pushgateway默认连接地址
  redis-url: "http://127.0.0.1:9093"          # redis默认连接地址

---
## 配置函数需要的密钥， 暂时没有启用
apiVersion: v1
kind: Secret
metadata:
  name: fission-function-global-configmap
  namespace: fission-secret-configmap
## 加密密钥， base64 编码，可以在终端中使用如下命令进行生成 `echo -n 'your content' | base64`
data:
  default: "ZGVmYXVsdA=="

## 明文密码
stringData:
  default: "default"